/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formAdmin;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import pesanDialog.BerhasilHapus;
import pesanDialog.BerhasilUbah;
import pesanDialog.GagalHapus;
import pesanDialog.GagalUbah;

/**
 *
 * @author HP
 */
public class FormAdminDetailStok extends javax.swing.JPanel {

    Connection conn;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form FormAdminDetailStok
     */
    public FormAdminDetailStok() {
        initComponents();
        table.fixTable(jScrollPane1);
        DefaultTableModel mode = (DefaultTableModel) table.getModel();
        table();
        id_menu.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_ubah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        id_menu = new javax.swing.JTextField();
        nama_menu = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new customtable.CustomTable();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1050, 520));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_ubah.setBackground(new java.awt.Color(255, 202, 73));
        btn_ubah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });
        add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 120, 40));

        btn_hapus.setBackground(new java.awt.Color(255, 61, 61));
        btn_hapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 120, 40));

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 460, -1, 30));

        id_menu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id_menu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                id_menuKeyReleased(evt);
            }
        });
        add(id_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 220, 30));
        add(nama_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 220, 30));

        harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hargaKeyReleased(evt);
            }
        });
        add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 220, 30));

        jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jumlahKeyReleased(evt);
            }
        });
        add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 220, 30));

        jButton2.setText("Refresh Table");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, 130, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, 290));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageForm/AdminDetailStok.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1050, 520));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "UPDATE stok_menu SET id_menu = '" + id_menu.getText() + "', nama_menu = '" + nama_menu.getText() + "',harga_menu = '" + harga.getText() + "',jumlah_menu = '" + jumlah.getText() + "' WHERE id_menu = " + id_menu.getText() + "";
            conn = (Connection) koneksi.configDB();
            pst = conn.prepareStatement(sql);
            pst.execute();
            BerhasilUbah ub = new BerhasilUbah();
            ub.setVisible(true);
            table();
        } catch (Exception e) {
            GagalUbah gu = new GagalUbah();
            gu.setVisible(true);
        }
        id_menu.setText("");
        nama_menu.setText("");
        harga.setText("");
        jumlah.setText("");
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "DELETE from stok_menu where id_menu = " + id_menu.getText();
            conn = (Connection) koneksi.configDB();
            pst = conn.prepareStatement(sql);
            pst.execute();
            BerhasilHapus bh = new BerhasilHapus();
            bh.setVisible(true);
        } catch (Exception e) {
            GagalHapus gh = new GagalHapus();
            gh.setVisible(true);
        }
        table();
        id_menu.setText("");
        nama_menu.setText("");
        harga.setText("");
        jumlah.setText("");
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FormAdminStockAvailable().setVisible(true);
        id_menu.setText("");
        nama_menu.setText("");
        harga.setText("");
        jumlah.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahKeyReleased
        // TODO add your handling code here:
        try {
            int har = Integer.parseInt(jumlah.getText());
        } catch (NumberFormatException ex) {
            jumlah.setText(null);
        }
    }//GEN-LAST:event_jumlahKeyReleased

    private void hargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargaKeyReleased
        // TODO add your handling code here:
        try {
            int har = Integer.parseInt(harga.getText());
        } catch (NumberFormatException ex) {
            harga.setText(null);
        }
    }//GEN-LAST:event_hargaKeyReleased

    private void id_menuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_menuKeyReleased
        // TODO add your handling code here:
        try {
            Statement state = conn.createStatement();
            String sql = "SELECT * FROM stok_menu WHERE id_menu = '" + id_menu.getText() + "'";
            conn = DriverManager.getConnection("jdbc:mysql://localhost/mbaknis", "root", "");
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            table();
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID Menu");
            model.addColumn("Jumlah Menu");
            model.addColumn("Nama Menu");
            model.addColumn("Harga");
            rs = state.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1),
                    rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)
                });
                table.setModel(model);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_id_menuKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        table();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField id_menu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField nama_menu;
    private customtable.CustomTable table;
    // End of variables declaration//GEN-END:variables

    public void table() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Menu");
        model.addColumn("Jumlah Menu");
        model.addColumn("Nama Menu");
        model.addColumn("Harga Menu");
        model.addColumn("Tanggal Penambahan Stok");

        try {
            String sql = "SELECT * FROM stok_menu";
            conn = DriverManager.getConnection("jdbc:mysql://localhost/mbaknis", "root", "");
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1),
                    rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)
                });
                table.setModel(model);
            }
        } catch (SQLException e) {
        }
    }
}
