/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormTransaction;

/**
 *
 * @author KRISNA
 */
public class FormMinuman extends javax.swing.JPanel {

    /**
     * Creates new form FormMakanan
     */
    public FormMinuman() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(stokm6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 60, -1));
        add(stokm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 60, -1));
        add(stokm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 60, -1));
        add(stokm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 60, -1));
        add(stokm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 60, -1));
        add(stokm5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 60, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageForm/FormMinuman.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public static final javax.swing.JTextField stokm1 = new javax.swing.JTextField();
    public static final javax.swing.JTextField stokm2 = new javax.swing.JTextField();
    public static final javax.swing.JTextField stokm3 = new javax.swing.JTextField();
    public static final javax.swing.JTextField stokm4 = new javax.swing.JTextField();
    public static final javax.swing.JTextField stokm5 = new javax.swing.JTextField();
    public static final javax.swing.JTextField stokm6 = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables
}
